#!/bin/sh
#
# $Id: dhcp3-server.init.d,v 1.4 2003/07/13 19:12:41 mdz Exp $
#
# On what interfaces should the DHCP server (dhcpd) serve DHCP requests?
#       Separate multiple interfaces with spaces, e.g. "eth0 eth1".
INTERFACES="eth0"

# Configuration file:
CONFIG_FILE="/etc/dhcp/dhcpd.conf"

function on_error {
 echo "Error"
 echo "Suggestion: launch yourself \`dhcpd -cf $CONFIG_FILE' for debugging."
}

set -e
trap on_error ERR

test -f /usr/sbin/dhcpd || exit 0

case "$1" in
	start)
		echo -n "Starting DHCP server: "
		test -d /var/lib/dhcp/ || mkdir -p /var/lib/dhcp/
		test -f /var/lib/dhcp/dhcpd.leases || touch /var/lib/dhcp/dhcpd.leases
		start-stop-daemon -S -x /usr/sbin/dhcpd -- -cf $CONFIG_FILE -q $INTERFACES
		echo "Ok."
		;;
	stop)
		echo -n "Stopping DHCP server: dhcpd3"
		start-stop-daemon -K -x /usr/sbin/dhcpd || true
		echo "Ok."
		;;
	restart | force-reload)
		$0 stop
		sleep 2
		$0 start
		if [ "$?" != "0" ]; then
			exit 1
		fi
		;;
	*)
		echo "Usage: /etc/init.d/dhcp-server {start|stop|restart|force-reload}"
		exit 1
esac

exit 0
